{% set name = "blosc-hdf5-plugin" %}
{% set version = "1.0.1" %}
{% set sha256 = "dcb249c007ed10b030e36d96bfc4404a2e45823eb8c3aae863e33d407e7b6cda" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  - url: https://github.com/Blosc/hdf5-blosc/archive/v{{ version }}.tar.gz
    folder: src
    sha256: {{ sha256 }}
  - path: cmake
    folder: src

build:
  number: 1
  skip: true  # [win]


requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}

  host:
    - hdf5
    - blosc
    - cmake
    - make
  run:
    - blosc
    - hdf5

test:
  files:
    - test_plugin.py
  requires:
    - h5py
    - python
  commands:
    - python test_plugin.py

about:
  license: 'BSD-3-Clause'
  license_file: 'LICENSE'
  home: https://github.com/Blosc/hdf5-blosc
  summary: HDF5 plugin for BLOSC filter
  description: |
    The plugin is being placed into HDF5 plugin directory, so it can be dynamically
    loaded. This enables the usage for other libraries like h5py. We use our own
    CMakeLists here to enable easy linking against Conda-Forges BLOSC library.

extra:
  recipe-maintainers:
    - marscher
    - tacaswell
