travis:
  secure:
    BINSTAR_TOKEN: bZbOfW2zRpKGVKYy425L9aRHTYAhtwZ6wKU0cOxa2o8aCUQP/OMCRFjX6pJv3TWXFVRmfM0CP83UgZMnEIr2RUZw+RreE7/pINuIY9DS2ssmWZ35Njn1giDFidKN37t//t13vBkfhrJ2atPNWVzNyQsGCRC8EBdYduBkzIccDib8ESWXN5oDzyp8xAKrBwpuh6MLVGtYMJK5OfSbEshFB7xW8ZIBH6Jjuk8yfPLfpqdYP3F6AMiozJcSGGX6UK/W+0LYG4IKiP5rCVb+a3Ahb/32m/qkK5xEiHF3AmXv4nI9VgZwyqNBT86b1hObFbIEPigVBgClwdie4nIBXUUXm3F3WQpTb3JSYSufKwghbRO1QXCKGULDNNdpkhju238PhYuEu8iU1jxqF6KZIAf2Gx5Bth2HydKk6VgbSG0GUzclcc4MywJ0QjFjUyuflu0Rz9fNAWMu2qOiSlyio8RKWPtCy5zgCFfM9WrGYAmFisxvH/NnfM0gMvTu2Qd0QasDtbnHyGDSIfH1oVhOAk1Cm+wKidSBqXh//Bs3Jl/3Pu6oVTXywfdsq+7mNZYBEmotHrM77mexadFMgSdCXhXO9xht2sk92k/gvy9en6j8OjwDXSUT44P0YE6HBrgdTcNiR5FPZ+ZCRS7mXe9iTOkv/PbpHpZTOL806ZodRuHumWg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
